"""
Interaction ORM model.

Represents a single logged interaction between a CRM user and a Doctor.

User-supplied fields:
    doctor_id, interaction_date, interaction_type, product_discussed,
    summary, notes, follow_up_date

AI-generated fields (populated asynchronously by LangGraph pipeline):
    ai_summary, ai_sentiment, ai_action_items, ai_processed

Audit fields:
    created_at, updated_at
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Interaction(Base):
    """A logged touchpoint between a CRM rep and a doctor."""

    __tablename__ = "interactions"

    # ── Primary key ────────────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True
    )

    # ── Foreign keys ───────────────────────────────────────────────────────────
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("doctors.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Core interaction fields (user-supplied) ────────────────────────────────
    interaction_date: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
        comment="Date and time the interaction took place",
    )
    interaction_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="visit | call | email | conference | virtual",
    )
    product_discussed: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        comment="Name of the pharmaceutical product discussed during the interaction",
    )
    summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="High-level summary written by the rep",
    )
    notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Detailed free-text notes from the rep",
    )
    follow_up_date: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        comment="Planned follow-up date set by the rep",
    )

    # ── Status ─────────────────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="draft",
        comment="draft | submitted | reviewed",
    )

    # ── AI-generated fields (populated by LangGraph pipeline) ─────────────────
    ai_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Concise summary generated by the AI pipeline",
    )
    ai_sentiment: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="positive | neutral | negative",
    )
    ai_action_items: Mapped[list[str] | None] = mapped_column(
        ARRAY(Text),
        nullable=True,
        comment="Follow-up action items extracted by the AI",
    )
    ai_follow_up_date: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="AI-suggested follow-up date (may differ from rep's follow_up_date)",
    )
    ai_processed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="True once the LangGraph pipeline has processed this record",
    )

    # ── Audit timestamps ───────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    doctor: Mapped["Doctor"] = relationship(  # noqa: F821
        "Doctor", back_populates="interactions"
    )
    user: Mapped["User"] = relationship(  # noqa: F821
        "User", back_populates="interactions"
    )

    def __repr__(self) -> str:
        return (
            f"<Interaction(id={self.id}, doctor_id={self.doctor_id}, "
            f"type={self.interaction_type}, date={self.interaction_date})>"
        )
