"""initial_tables

Revision ID: 282b82e41721
Revises: 
Create Date: 2026-07-11 21:52:30.212116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '282b82e41721'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('interaction_date', sa.DateTime(timezone=True), nullable=False, comment='Date and time the interaction took place'),
    sa.Column('interaction_type', sa.String(length=50), nullable=False, comment='visit | call | email | conference | virtual'),
    sa.Column('product_discussed', sa.String(length=255), nullable=True, comment='Name of the pharmaceutical product discussed during the interaction'),
    sa.Column('summary', sa.Text(), nullable=True, comment='High-level summary written by the rep'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Detailed free-text notes from the rep'),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True, comment='Planned follow-up date set by the rep'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='draft | submitted | reviewed'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='Concise summary generated by the AI pipeline'),
    sa.Column('ai_sentiment', sa.String(length=20), nullable=True, comment='positive | neutral | negative'),
    sa.Column('ai_action_items', postgresql.ARRAY(sa.Text()), nullable=True, comment='Follow-up action items extracted by the AI'),
    sa.Column('ai_follow_up_date', sa.DateTime(timezone=True), nullable=True, comment="AI-suggested follow-up date (may differ from rep's follow_up_date)"),
    sa.Column('ai_processed', sa.Boolean(), nullable=False, comment='True once the LangGraph pipeline has processed this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_doctor_id'), 'interactions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_interactions_follow_up_date'), 'interactions', ['follow_up_date'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_interaction_date'), 'interactions', ['interaction_date'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_interaction_date'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_follow_up_date'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_doctor_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
