"""
Pydantic schemas for the Interaction resource.

Request schemas:
    InteractionCreate   POST /interactions
    InteractionUpdate   PUT  /interactions/{id}   (full replace, all writable fields required)
    InteractionPatch    PATCH /interactions/{id}  (partial update, all optional)

Response schemas:
    InteractionRead     full record (all fields, nested DoctorSummary)
    InteractionSummary  lightweight record for list endpoints
    InteractionPage     paginated list wrapper
"""

import uuid
from datetime import datetime
from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from app.schemas.doctor import DoctorSummary

# ── Enum literals enforced at the API boundary ────────────────────────────────
InteractionTypeEnum = Literal["visit", "call", "email", "conference", "virtual"]
StatusEnum = Literal["draft", "submitted", "reviewed"]
SentimentEnum = Literal["positive", "neutral", "negative"]


# ── Shared base ───────────────────────────────────────────────────────────────
class InteractionBase(BaseModel):
    """Fields that appear in both requests and responses."""

    doctor_id: uuid.UUID = Field(
        ...,
        description="ID of the doctor this interaction was with",
    )
    interaction_date: datetime = Field(
        ...,
        description="Date and time the interaction took place (ISO 8601)",
        examples=["2026-07-09T10:30:00+05:30"],
    )
    interaction_type: InteractionTypeEnum = Field(
        ...,
        description="Nature of the interaction",
        examples=["visit"],
    )
    product_discussed: Optional[str] = Field(
        None,
        max_length=255,
        description="Pharmaceutical product discussed during the interaction",
        examples=["Cardivol 10mg"],
    )
    summary: Optional[str] = Field(
        None,
        description="High-level summary written by the rep",
        examples=["Doctor expressed strong interest in the new formulation."],
    )
    notes: Optional[str] = Field(
        None,
        description="Detailed free-text notes from the rep",
        examples=["Dr. Sharma raised concerns about side effects. Shared Phase III data."],
    )
    follow_up_date: Optional[datetime] = Field(
        None,
        description="Follow-up date planned by the rep",
        examples=["2026-07-23T10:00:00+05:30"],
    )
    status: StatusEnum = Field(
        default="draft",
        description="Workflow status of the interaction log",
    )


# ── POST — create ──────────────────────────────────────────────────────────────
class InteractionCreate(InteractionBase):
    """
    Payload for POST /interactions.
    Required: doctor_id, interaction_date, interaction_type.
    All other fields are optional.
    """
    pass


# ── PUT — full replace ────────────────────────────────────────────────────────
class InteractionUpdate(InteractionBase):
    """
    Payload for PUT /interactions/{id}.
    Replaces the entire writable portion of the record.
    Same required fields as InteractionCreate.
    doctor_id cannot be changed — it is validated in the service layer.
    """
    pass


# ── PATCH — partial update ────────────────────────────────────────────────────
class InteractionPatch(BaseModel):
    """
    Payload for PATCH /interactions/{id}.
    Every field is optional — only provided fields are updated.
    doctor_id is excluded (cannot change the doctor of an existing interaction).
    """
    interaction_date: Optional[datetime] = None
    interaction_type: Optional[InteractionTypeEnum] = None
    product_discussed: Optional[str] = Field(None, max_length=255)
    summary: Optional[str] = None
    notes: Optional[str] = None
    follow_up_date: Optional[datetime] = None
    status: Optional[StatusEnum] = None


# ── GET (single) — full response ──────────────────────────────────────────────
class InteractionRead(InteractionBase):
    """
    Full interaction record returned to the client.
    Includes rep-supplied fields, AI-generated fields, and audit timestamps.
    """
    id: uuid.UUID
    user_id: Optional[uuid.UUID] = None

    # Nested doctor (avoids a second HTTP round-trip from the frontend)
    doctor: Optional[DoctorSummary] = None

    # ── AI-generated fields (populated by LangGraph pipeline) ─────────────────
    ai_summary: Optional[str] = Field(
        None,
        description="Concise summary generated by the AI pipeline",
    )
    ai_sentiment: Optional[SentimentEnum] = Field(
        None,
        description="Sentiment detected by the AI: positive | neutral | negative",
    )
    ai_action_items: Optional[List[str]] = Field(
        None,
        description="Follow-up action items extracted by the AI",
    )
    ai_follow_up_date: Optional[datetime] = Field(
        None,
        description="AI-suggested follow-up date",
    )
    ai_processed: bool = Field(
        default=False,
        description="True once the LangGraph AI pipeline has processed this record",
    )

    # ── Audit timestamps ───────────────────────────────────────────────────────
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


# ── GET (list) — lightweight response ────────────────────────────────────────
class InteractionSummary(BaseModel):
    """
    Lightweight interaction record for paginated list endpoints.
    Excludes heavy text fields (notes, summary, ai_action_items) to keep
    list payloads small.
    """
    id: uuid.UUID
    doctor_id: uuid.UUID
    doctor: Optional[DoctorSummary] = None
    interaction_date: datetime
    interaction_type: InteractionTypeEnum
    product_discussed: Optional[str] = None
    status: StatusEnum
    ai_processed: bool
    ai_sentiment: Optional[SentimentEnum] = None
    follow_up_date: Optional[datetime] = None
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Paginated list wrapper ────────────────────────────────────────────────────
class InteractionPage(BaseModel):
    """
    Paginated response envelope for GET /interactions.

    Example response:
    {
        "items": [...],
        "total": 48,
        "skip": 0,
        "limit": 20,
        "page": 1,
        "pages": 3
    }
    """
    items: List[InteractionSummary]
    total: int = Field(..., description="Total number of matching records")
    skip: int = Field(..., description="Number of records skipped")
    limit: int = Field(..., description="Max records per page")
    page: int = Field(..., description="Current page (1-based)")
    pages: int = Field(..., description="Total number of pages")
